# 텐서(tensor)
tensor : 배열(array), 행렬(matrix)과 매우 유사한 자료구조. pyTorch에서는 텐서를 사용하여 모델의 입/출력, 모델의 매개변수들을 부호화(encode)<br>
실제로 tensor와 NumPy의 배열(array)은 종종 동일한 메모리를 공유할 수 있어 데이터를 복사할 필요가 없음.<br>
tensor는 또한 자동미분에 최적화

In [1]:
import torch
import numpy as np

## tensor초기화
- tensor의 경우 여러 방법으로 초기화 가능

In [2]:
# 1. 데이터로부터 직접 생성

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
# 2. Numpy 배열로부터 생성하기

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# 3. 다른 tensor로 부터 생성하기
#    명시적으로 재정의하지 않는경우 인자로 주어진 텐서의 속성(모양,자료형)을 유지

x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 변환.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7650, 0.0220],
        [0.1220, 0.5971]]) 



In [5]:
# 4. 무작위 또는 상수값 사용

shape = (2, 3, )
rand_tensor = torch.rand(shape) # 랜덤값 
ones_tensor = torch.ones(shape) # 1값
zeros_tensor = torch.zeros(shape) # 0값

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7492, 0.5974, 0.1893],
        [0.8018, 0.8045, 0.7267]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## tensor의 속성
- tensor의 속성은 모양(shape), 자료형(datatype)및 어느 장치에 저장되는지 나타냄

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}") # shape
print(f"Datatype of tensor: {tensor.dtype}") # Dtype
print(f"Device tensor is stored on: {tensor.device}") # 저장위치

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## tensor 연산
- 전치(transposing), 인덱싱(indexing), 슬라이싱(slicing) 수학계산, 선형대수, 임의샘플링 등 tensor 연산 가능
- 기본적으로 tensor는 CPU에 생성, .to 메서드를 사용하면 GPU로 tensor를 명시적으로 이동 가능.

In [8]:
# GPU가 존재하면 텐서를 이동.

if torch.cuda.is_available():
    tensor = tensor.to("cuda")
else:
    print("not usable") #GPU가 없는경우 출력

not usable
