# 텐서(tensor)
tensor : 배열(array), 행렬(matrix)과 매우 유사한 자료구조. pyTorch에서는 텐서를 사용하여 모델의 입/출력, 모델의 매개변수들을 부호화(encode)<br>
실제로 tensor와 NumPy의 배열(array)은 종종 동일한 메모리를 공유할 수 있어 데이터를 복사할 필요가 없음.<br>
tensor는 또한 자동미분에 최적화

In [1]:
import torch
import numpy as np

## tensor초기화
- tensor의 경우 여러 방법으로 초기화 가능

In [2]:
# 1. 데이터로부터 직접 생성

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
# 2. Numpy 배열로부터 생성하기

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# 3. 다른 tensor로 부터 생성하기
#    명시적으로 재정의하지 않는경우 인자로 주어진 텐서의 속성(모양,자료형)을 유지

x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 변환.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6407, 0.2535],
        [0.1566, 0.3907]]) 



In [5]:
# 4. 무작위 또는 상수값 사용

shape = (2, 3, )
rand_tensor = torch.rand(shape) # 랜덤값 
ones_tensor = torch.ones(shape) # 1값
zeros_tensor = torch.zeros(shape) # 0값

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2106, 0.3181, 0.4336],
        [0.0529, 0.3168, 0.0535]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## tensor의 속성
- tensor의 속성은 모양(shape), 자료형(datatype)및 어느 장치에 저장되는지 나타냄

In [6]:
tensor = torch.rand(3,4)

print(tensor)
print(f"Shape of tensor: {tensor.shape}") # shape
print(f"Datatype of tensor: {tensor.dtype}") # Dtype
print(f"Device tensor is stored on: {tensor.device}") # 저장위치

tensor([[0.3506, 0.1108, 0.8268, 0.0819],
        [0.5886, 0.9464, 0.6833, 0.1212],
        [0.9839, 0.9667, 0.0623, 0.6912]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## tensor 연산
- 전치(transposing), 인덱싱(indexing), 슬라이싱(slicing) 수학계산, 선형대수, 임의샘플링 등 tensor 연산 가능
- 기본적으로 tensor는 CPU에 생성, .to 메서드를 사용하면 GPU로 tensor를 명시적으로 이동 가능.

In [7]:
# GPU가 존재하면 텐서를 이동.

if torch.cuda.is_available():
    tensor = tensor.to("cuda")
else:
    print("not usable") #GPU가 없는경우 출력

not usable


numpy식 표준 인덱싱, 슬라이싱

In [12]:
tensor = torch.rand(4, 4)

print(tensor)
print(f"first row : {tensor[0]}")
print(f"first column : {tensor[:,0]}")
print(f"last column : {tensor[..., -1]}")

tensor([[0.3556, 0.9199, 0.5411, 0.7954],
        [0.2764, 0.3899, 0.1533, 0.0477],
        [0.5737, 0.2577, 0.4229, 0.3384],
        [0.2880, 0.2066, 0.1863, 0.3140]])
first row : tensor([0.3556, 0.9199, 0.5411, 0.7954])
first column : tensor([0.3556, 0.2764, 0.5737, 0.2880])
last column : tensor([0.7954, 0.0477, 0.3384, 0.3140])


tensor 합치기

In [17]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1) #dim = 1 (열방향 연결)
print(t1)

tensor([[0.3556, 0.9199, 0.5411, 0.7954, 0.3556, 0.9199, 0.5411, 0.7954, 0.3556,
         0.9199, 0.5411, 0.7954],
        [0.2764, 0.3899, 0.1533, 0.0477, 0.2764, 0.3899, 0.1533, 0.0477, 0.2764,
         0.3899, 0.1533, 0.0477],
        [0.5737, 0.2577, 0.4229, 0.3384, 0.5737, 0.2577, 0.4229, 0.3384, 0.5737,
         0.2577, 0.4229, 0.3384],
        [0.2880, 0.2066, 0.1863, 0.3140, 0.2880, 0.2066, 0.1863, 0.3140, 0.2880,
         0.2066, 0.1863, 0.3140]])


tensor 연산

In [21]:
# 텐서간의 행렬 곱 계산(y1, y2, y3는 같은값을 갖는다)

y1 = tensor @ tensor.T # @ : 행렬간의 곱셈을 나타냄
print(y1)

y2 = tensor.matmul(tensor.T) # 텐서와 텐서의 전치행렬의 곱 (y1과 같음)
print(y2)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[1.8980, 0.5778, 0.9390, 0.6430],
        [0.5778, 0.2542, 0.3400, 0.2037],
        [0.9390, 0.3400, 0.6889, 0.4035],
        [0.6430, 0.2037, 0.4035, 0.2589]])
tensor([[1.8980, 0.5778, 0.9390, 0.6430],
        [0.5778, 0.2542, 0.3400, 0.2037],
        [0.9390, 0.3400, 0.6889, 0.4035],
        [0.6430, 0.2037, 0.4035, 0.2589]])


tensor([[1.8980, 0.5778, 0.9390, 0.6430],
        [0.5778, 0.2542, 0.3400, 0.2037],
        [0.9390, 0.3400, 0.6889, 0.4035],
        [0.6430, 0.2037, 0.4035, 0.2589]])

단일요소 tensor : tensor의 모든값을 하나로 집계, item() 을 사용하여 python 숫자값으로 변환 가능

In [24]:
agg = tensor.sum()
agg_item = agg.item()

print(agg, agg_item, type(agg_item))

tensor(6.0668) 6.066757678985596 <class 'float'>


in_place 연산 : 연산결과를 저장, _ 접미사를 갖는다. <br>
ex) x.copy_(y) 나 x.t_()는 x를 변경

In [25]:
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)

tensor([[0.3556, 0.9199, 0.5411, 0.7954],
        [0.2764, 0.3899, 0.1533, 0.0477],
        [0.5737, 0.2577, 0.4229, 0.3384],
        [0.2880, 0.2066, 0.1863, 0.3140]])

tensor([[5.3556, 5.9199, 5.5411, 5.7954],
        [5.2764, 5.3899, 5.1533, 5.0477],
        [5.5737, 5.2577, 5.4229, 5.3384],
        [5.2880, 5.2066, 5.1863, 5.3140]])


## Numpy변환
- CPU상의 tensor와 Numpy배열은 메모리 공간을 공유, 하나를 변경시 다른 하나도 변경

tensor를 Numpy배열로 변환

In [29]:
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [30]:
# tensor 의 변경사항이 Numpy 배열에 반영
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


Numpy배열을 tensor로 변환

In [32]:
np.add(n, 1, out = n) # out = n : 결과값을 n에 다시 저장
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]
